#######
# see https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/alpine/Dockerfile
#######

FROM docker:17.12.0-ce as static-docker-source

FROM alpine:latest

#######
# original cron tasks
#######
RUN apk update 
RUN apk add bash python python-dev py-pip build-base openssl-dev libffi-dev dcron curl wget rsync ca-certificates iputils vim bind-tools openssh-client nfs-utils
RUN apk add --no-cache python3
RUN rm -rf /var/cache/apk/*
RUN mkdir -p /var/log/cron && mkdir -m 0644 -p /var/spool/cron/crontabs && touch /var/log/cron/cron.log && mkdir -m 0644 -p /etc/cron.d
RUN mkdir -p /scripts
RUN mkdir -p /tank
RUN apk add tzdata && cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && echo "Europe/Vienna" > /etc/timezone && apk del tzdata

COPY /startup/* /
RUN chmod +x /docker-entry.sh
RUN chmod +x /docker-cmd.sh

#######
# cloud-sdk-docker container tasks
#######
ARG CLOUD_SDK_VERSION=292.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV CLOUDSDK_PYTHON=python3

ENV PATH /google-cloud-sdk/bin:$PATH
COPY --from=static-docker-source /usr/local/bin/docker /usr/local/bin/docker
RUN apk --no-cache add \
        py3-crcmod \
        libc6-compat \
        git \
        gnupg \
    && curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version
VOLUME ["/root/.config"]

#######
# finish
#######
ENTRYPOINT ["/docker-entry.sh"]
CMD ["/docker-cmd.sh"]
